Repository substandardApartment-V2/BE, pull requests merged in 2025-02, with the labels that each got.

#37 [FEAT] 지도 마커 불러오기 API 관련
  Dockerfile
  db/data.sql
  src/main/java/com/myapt/domain/apt/controller/MapController.java
  src/main/java/com/myapt/domain/apt/entity/Apts.java
  src/main/java/com/myapt/domain/apt/repository/AptRepository.java
  src/main/java/com/myapt/domain/apt/service/MapService.java
  src/main/java/com/myapt/domain/apt/service/MapServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#42 :bug: Feat[#11]
  src/main/java/com/myapt/domain/apt/entity/DetailApts.java
  src/main/java/com/myapt/domain/apt/service/AptServiceImpl.java
Labels: 🐞 Bug

#47 [FEAT] 뉴스 API 고도화 - 본문 늘리기 및 이미지 null 처리
  src/main/java/com/myapt/domain/news/dto/NewsApiResponse.java
  src/main/java/com/myapt/domain/news/dto/NewsSummaryDto.java
  src/main/java/com/myapt/domain/news/service/NewsServiceImpl.java
  src/main/java/com/myapt/domain/news/util/JsoupCrawling.java
Labels: ✨ Feature, 🔨 Refactor

#48 [FEAT] 뉴스 API 고도화 - 플랫폼 추출 및 이미지 null 처리
  src/main/java/com/myapt/domain/news/dto/NewsApiResponse.java
  src/main/java/com/myapt/domain/news/dto/NewsCrawlingResponse.java
  src/main/java/com/myapt/domain/news/dto/NewsSummaryDto.java
  src/main/java/com/myapt/domain/news/service/NewsServiceImpl.java
  src/main/java/com/myapt/domain/news/util/JsoupCrawling.java
Labels: ✨ Feature, 🔨 Refactor

#49 [FEAT] 지도 API 수정
  src/main/java/com/myapt/domain/apt/controller/MapController.java
  src/main/java/com/myapt/domain/apt/dto/MapSearchInfo.java
  src/main/java/com/myapt/domain/apt/dto/SearchResponse.java
  src/main/java/com/myapt/domain/apt/repository/AptRepository.java
  src/main/java/com/myapt/domain/apt/service/MapService.java
  src/main/java/com/myapt/domain/apt/service/MapServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#45 Feat/main #20
  build.gradle
  src/main/java/com/myapt/domain/apt/controller/AptController.java
  src/main/java/com/myapt/domain/apt/controller/CsvController.java
  src/main/java/com/myapt/domain/apt/dto/MainResponse.java
  src/main/java/com/myapt/domain/apt/entity/AvgPrices.java
  src/main/java/com/myapt/domain/apt/entity/PlannedApts.java
  src/main/java/com/myapt/domain/apt/repository/AvgPricesRepository.java
  src/main/java/com/myapt/domain/apt/repository/PlannedAptsRepository.java
  src/main/java/com/myapt/domain/apt/service/AptServiceImpl.java
  src/main/java/com/myapt/domain/apt/service/CsvService.java
  src/main/java/com/myapt/domain/apt/service/CsvServiceImpl.java
Labels: ✨ Feature
