Repository substandardApartment-V2/BE, pull requests merged in 2025-03, with the labels that each got.

#57 Fix[#9]: 중복 뉴스 처리 로직 개선 및 pubDate 필드 추가
  src/main/java/com/myapt/domain/news/dto/NewsCrawlingResponse.java
  src/main/java/com/myapt/domain/news/dto/NewsSummaryDto.java
  src/main/java/com/myapt/domain/news/entity/News.java
  src/main/java/com/myapt/domain/news/repository/NewsRepository.java
  src/main/java/com/myapt/domain/news/service/NewsServiceImpl.java
Labels: 🐞 Bug, ✨ Feature

#59 [FEAT] 지도좌표 API Response 주소 추가 관련
  src/main/java/com/myapt/domain/apt/dto/MapMarkerInfo.java
  src/main/java/com/myapt/domain/apt/service/MapServiceImpl.java
Labels: ✨ Feature

#63 Feat/apt #62
  src/main/java/com/myapt/domain/apt/dto/AptInfo.java
  src/main/java/com/myapt/domain/apt/dto/AptInfoDetail.java
  src/main/java/com/myapt/domain/apt/dto/MngCostInfo.java
  src/main/java/com/myapt/domain/apt/service/AptServiceImpl.java
Labels: 🔨 Refactor

#71 Feat/apt #50
  Dockerfile
  build.gradle
  db/data.sql
  docker-compose.yml
  src/main/java/com/myapt/MyaptApplication.java
  src/main/java/com/myapt/domain/apt/controller/CsvController.java
  src/main/java/com/myapt/domain/apt/entity/AvgPrices.java
  src/main/java/com/myapt/domain/apt/entity/PlannedApts.java
  src/main/java/com/myapt/domain/apt/repository/AvgPricesRepository.java
  src/main/java/com/myapt/domain/apt/repository/PlannedAptsRepository.java
  src/main/java/com/myapt/domain/apt/service/AptServiceImpl.java
  src/main/java/com/myapt/domain/apt/service/CsvService.java
  src/main/java/com/myapt/domain/apt/service/CsvServiceImpl.java
  src/main/java/com/myapt/global/config/WebConfig.java
  src/main/resources/application.yml
  src/test/java/com/myapt/MyaptApplicationTests.java
Labels: 🐞 Bug, 🔨 Refactor

#75 Fix[#72] 뉴스 HTML 문서 미수집 시 플랫폼,이미지 매핑 오류 수정
  src/main/java/com/myapt/domain/news/dto/NewsSummaryDto.java
  src/main/java/com/myapt/domain/news/enums/NewsPlatform.java
  src/main/java/com/myapt/domain/news/util/JsoupCrawling.java
Labels: 🐞 Bug, 🔨 Refactor

#74 ♻️ Feat[#69]: 예외 처리 & Valid 검증 로직 추가
  build.gradle
  src/main/java/com/myapt/domain/apt/controller/AptController.java
  src/main/java/com/myapt/domain/apt/controller/MapController.java
  src/main/java/com/myapt/domain/apt/dto/NoticeRequest.java
  src/main/java/com/myapt/domain/apt/exception/MainInvalidException.java
  src/main/java/com/myapt/domain/apt/exception/MainNotFoundException.java
  src/main/java/com/myapt/domain/apt/exception/MapInvalidException.java
  src/main/java/com/myapt/domain/apt/exception/MapNotFoundException.java
  src/main/java/com/myapt/domain/apt/exception/MarkerNotFoundException.java
  src/main/java/com/myapt/domain/apt/exception/NoticeNotFoundException.java
  src/main/java/com/myapt/domain/apt/service/AptServiceImpl.java
  src/main/java/com/myapt/domain/apt/service/MapService.java
  src/main/java/com/myapt/domain/apt/service/MapServiceImpl.java
  src/main/java/com/myapt/domain/defect/exception/DefectAptInvalidException.java
  src/main/java/com/myapt/domain/defect/exception/DefectAptNotFoundException.java
  src/main/java/com/myapt/domain/defect/service/DefectServiceImpl.java
  src/main/java/com/myapt/domain/news/controller/NewsController.java
  src/main/java/com/myapt/domain/news/dto/NewsPageRequest.java
  src/main/java/com/myapt/domain/news/exception/NaverApiCallException.java
  src/main/java/com/myapt/domain/news/exception/NewsNotFoundException.java
  src/main/java/com/myapt/domain/news/exception/NewsNullException.java
  src/main/java/com/myapt/domain/news/exception/NewsTypeNotFoundException.java
  src/main/java/com/myapt/domain/news/repository/NewsApiResponseRepository.java
  src/main/java/com/myapt/domain/news/service/NewsServiceImpl.java
  src/main/java/com/myapt/global/config/WebConfig.java
  src/main/java/com/myapt/global/error/ControllerAdvice.java
  src/main/java/com/myapt/global/error/annotations/AllowedSortValues.java
  src/main/java/com/myapt/global/error/validator/AllowedValuesValidator.java
  src/main/resources/ValidationMessages.properties
  src/main/resources/application.yml
Labels: ✨ Feature, 🔨 Refactor

#78 Refactor[#76] 뉴스 중복 문제 해결
  src/main/java/com/myapt/domain/news/entity/News.java
  src/main/java/com/myapt/domain/news/repository/NewsJdbcRepository.java
  src/main/java/com/myapt/domain/news/service/NewsServiceImpl.java
Labels: 🐞 Bug, 🔨 Refactor
